# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\test\ui\Xrun.ui'
#
# Created: Thu Dec 22 10:10:09 2016
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(563, 469)
        self.ovens_check = QtGui.QCheckBox(Form)
        self.ovens_check.setGeometry(QtCore.QRect(20, 30, 70, 17))
        self.ovens_check.setObjectName("ovens_check")
        self.power_check = QtGui.QCheckBox(Form)
        self.power_check.setGeometry(QtCore.QRect(20, 80, 70, 17))
        self.power_check.setObjectName("power_check")
        self.power_wdt = QtGui.QCheckBox(Form)
        self.power_wdt.setGeometry(QtCore.QRect(510, 80, 16, 21))
        self.power_wdt.setText("")
        self.power_wdt.setObjectName("power_wdt")
        self.label = QtGui.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(500, 10, 41, 20))
        self.label.setObjectName("label")
        self.ovens_wdt = QtGui.QCheckBox(Form)
        self.ovens_wdt.setGeometry(QtCore.QRect(510, 30, 16, 21))
        self.ovens_wdt.setStyleSheet("")
        self.ovens_wdt.setText("")
        self.ovens_wdt.setObjectName("ovens_wdt")
        self.power_cur = QtGui.QLCDNumber(Form)
        self.power_cur.setGeometry(QtCore.QRect(280, 80, 64, 23))
        self.power_cur.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.power_cur.setObjectName("power_cur")
        self.ovens_set = QtGui.QLCDNumber(Form)
        self.ovens_set.setGeometry(QtCore.QRect(190, 30, 64, 23))
        self.ovens_set.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.ovens_set.setObjectName("ovens_set")
        self.power_vol = QtGui.QLCDNumber(Form)
        self.power_vol.setGeometry(QtCore.QRect(190, 80, 64, 23))
        self.power_vol.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.power_vol.setObjectName("power_vol")
        self.ovens_info = QtGui.QLabel(Form)
        self.ovens_info.setGeometry(QtCore.QRect(360, 30, 101, 16))
        self.ovens_info.setObjectName("ovens_info")
        self.power_info = QtGui.QLabel(Form)
        self.power_info.setGeometry(QtCore.QRect(360, 80, 111, 16))
        self.power_info.setObjectName("power_info")
        self.ovens_real = QtGui.QLCDNumber(Form)
        self.ovens_real.setGeometry(QtCore.QRect(280, 30, 64, 23))
        self.ovens_real.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.ovens_real.setObjectName("ovens_real")
        self.jdsu_check = QtGui.QCheckBox(Form)
        self.jdsu_check.setGeometry(QtCore.QRect(20, 130, 70, 21))
        self.jdsu_check.setObjectName("jdsu_check")
        self.jdsu_tx = QtGui.QLCDNumber(Form)
        self.jdsu_tx.setGeometry(QtCore.QRect(190, 130, 301, 23))
        self.jdsu_tx.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.jdsu_tx.setObjectName("jdsu_tx")
        self.jdsu_error = QtGui.QLCDNumber(Form)
        self.jdsu_error.setGeometry(QtCore.QRect(190, 180, 301, 23))
        self.jdsu_error.setStyleSheet("background-color: rgb(0, 85, 255);")
        self.jdsu_error.setObjectName("jdsu_error")
        self.jdsu_wdt = QtGui.QCheckBox(Form)
        self.jdsu_wdt.setGeometry(QtCore.QRect(510, 130, 16, 21))
        self.jdsu_wdt.setStyleSheet("")
        self.jdsu_wdt.setText("")
        self.jdsu_wdt.setObjectName("jdsu_wdt")
        self.label_2 = QtGui.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(210, 10, 46, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(290, 10, 46, 13))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtGui.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(210, 60, 46, 13))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(290, 60, 46, 13))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtGui.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(200, 110, 31, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtGui.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(200, 160, 61, 16))
        self.label_7.setObjectName("label_7")
        self.laser_on = QtGui.QPushButton(Form)
        self.laser_on.setGeometry(QtCore.QRect(20, 180, 61, 23))
        self.laser_on.setObjectName("laser_on")
        self.test_on = QtGui.QPushButton(Form)
        self.test_on.setGeometry(QtCore.QRect(110, 180, 61, 23))
        self.test_on.setObjectName("test_on")
        self.ovens_addr = QtGui.QLineEdit(Form)
        self.ovens_addr.setGeometry(QtCore.QRect(70, 30, 113, 20))
        self.ovens_addr.setObjectName("ovens_addr")
        self.power_addr = QtGui.QLineEdit(Form)
        self.power_addr.setGeometry(QtCore.QRect(70, 80, 113, 20))
        self.power_addr.setObjectName("power_addr")
        self.jdsu_addr = QtGui.QLineEdit(Form)
        self.jdsu_addr.setGeometry(QtCore.QRect(70, 130, 113, 20))
        self.jdsu_addr.setObjectName("jdsu_addr")
        self.led_sync = QtGui.QToolButton(Form)
        self.led_sync.setGeometry(QtCore.QRect(20, 158, 151, 21))
        self.led_sync.setObjectName("led_sync")
        self.imb1_check = QtGui.QCheckBox(Form)
        self.imb1_check.setGeometry(QtCore.QRect(20, 230, 70, 21))
        self.imb1_check.setObjectName("imb1_check")
        self.imb1_addr = QtGui.QLineEdit(Form)
        self.imb1_addr.setGeometry(QtCore.QRect(80, 230, 113, 20))
        self.imb1_addr.setObjectName("imb1_addr")
        self.imb1_wdt = QtGui.QCheckBox(Form)
        self.imb1_wdt.setGeometry(QtCore.QRect(510, 230, 16, 21))
        self.imb1_wdt.setStyleSheet("")
        self.imb1_wdt.setText("")
        self.imb1_wdt.setObjectName("imb1_wdt")
        self.lc1_check = QtGui.QCheckBox(Form)
        self.lc1_check.setGeometry(QtCore.QRect(20, 330, 70, 21))
        self.lc1_check.setObjectName("lc1_check")
        self.lc1_addr = QtGui.QLineEdit(Form)
        self.lc1_addr.setGeometry(QtCore.QRect(80, 330, 113, 20))
        self.lc1_addr.setObjectName("lc1_addr")
        self.lc1_wdt = QtGui.QCheckBox(Form)
        self.lc1_wdt.setGeometry(QtCore.QRect(510, 330, 16, 21))
        self.lc1_wdt.setStyleSheet("")
        self.lc1_wdt.setText("")
        self.lc1_wdt.setObjectName("lc1_wdt")
        self.lc2_check = QtGui.QCheckBox(Form)
        self.lc2_check.setGeometry(QtCore.QRect(20, 380, 70, 21))
        self.lc2_check.setObjectName("lc2_check")
        self.lc2_addr = QtGui.QLineEdit(Form)
        self.lc2_addr.setGeometry(QtCore.QRect(80, 380, 113, 20))
        self.lc2_addr.setObjectName("lc2_addr")
        self.lc2_wdt = QtGui.QCheckBox(Form)
        self.lc2_wdt.setGeometry(QtCore.QRect(510, 380, 16, 21))
        self.lc2_wdt.setStyleSheet("")
        self.lc2_wdt.setText("")
        self.lc2_wdt.setObjectName("lc2_wdt")
        self.imb2_check = QtGui.QCheckBox(Form)
        self.imb2_check.setGeometry(QtCore.QRect(20, 280, 70, 21))
        self.imb2_check.setObjectName("imb2_check")
        self.imb2_addr = QtGui.QLineEdit(Form)
        self.imb2_addr.setGeometry(QtCore.QRect(80, 280, 113, 20))
        self.imb2_addr.setObjectName("imb2_addr")
        self.imb2_wdt = QtGui.QCheckBox(Form)
        self.imb2_wdt.setGeometry(QtCore.QRect(510, 280, 16, 21))
        self.imb2_wdt.setStyleSheet("")
        self.imb2_wdt.setText("")
        self.imb2_wdt.setObjectName("imb2_wdt")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(QtGui.QApplication.translate("Form", "Xrun", None, QtGui.QApplication.UnicodeUTF8))
        self.ovens_check.setText(QtGui.QApplication.translate("Form", "Ovens", None, QtGui.QApplication.UnicodeUTF8))
        self.power_check.setText(QtGui.QApplication.translate("Form", "Power", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Form", " WDT", None, QtGui.QApplication.UnicodeUTF8))
        self.ovens_info.setText(QtGui.QApplication.translate("Form", "IDLE", None, QtGui.QApplication.UnicodeUTF8))
        self.power_info.setText(QtGui.QApplication.translate("Form", "IDLE", None, QtGui.QApplication.UnicodeUTF8))
        self.jdsu_check.setText(QtGui.QApplication.translate("Form", "JDSU", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Form", "SET", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Form", "TEMP", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Form", "VOL", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Form", "CUR", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Form", "TX BIT", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Form", "BIT ERROR", None, QtGui.QApplication.UnicodeUTF8))
        self.laser_on.setText(QtGui.QApplication.translate("Form", "LASER ON", None, QtGui.QApplication.UnicodeUTF8))
        self.test_on.setText(QtGui.QApplication.translate("Form", "TEST ON", None, QtGui.QApplication.UnicodeUTF8))
        self.ovens_addr.setText(QtGui.QApplication.translate("Form", "10.220.52.40:10004", None, QtGui.QApplication.UnicodeUTF8))
        self.power_addr.setText(QtGui.QApplication.translate("Form", "10.220.52.111", None, QtGui.QApplication.UnicodeUTF8))
        self.jdsu_addr.setText(QtGui.QApplication.translate("Form", "10.220.52.74", None, QtGui.QApplication.UnicodeUTF8))
        self.led_sync.setText(QtGui.QApplication.translate("Form", "SYNC", None, QtGui.QApplication.UnicodeUTF8))
        self.imb1_check.setText(QtGui.QApplication.translate("Form", "IMB1", None, QtGui.QApplication.UnicodeUTF8))
        self.imb1_addr.setText(QtGui.QApplication.translate("Form", "10.220.52.40:10001", None, QtGui.QApplication.UnicodeUTF8))
        self.lc1_check.setText(QtGui.QApplication.translate("Form", "LC1", None, QtGui.QApplication.UnicodeUTF8))
        self.lc1_addr.setText(QtGui.QApplication.translate("Form", "10.220.52.40:10002", None, QtGui.QApplication.UnicodeUTF8))
        self.lc2_check.setText(QtGui.QApplication.translate("Form", "LC2", None, QtGui.QApplication.UnicodeUTF8))
        self.lc2_addr.setText(QtGui.QApplication.translate("Form", "10.220.52.40:10003", None, QtGui.QApplication.UnicodeUTF8))
        self.imb2_check.setText(QtGui.QApplication.translate("Form", "IMB2", None, QtGui.QApplication.UnicodeUTF8))
        self.imb2_addr.setText(QtGui.QApplication.translate("Form", "10.220.52.40:10001", None, QtGui.QApplication.UnicodeUTF8))

